FROM golang:1.10.2-alpine

RUN apk add --no-cache git bash && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/golang/lint/golint

WORKDIR /go/src/aws-sam-golang-docker/
COPY . /go/src/aws-sam-golang-docker/
RUN dep ensure

CMD CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o ./main ./main.go
